name: Deploy to K3s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t arkintel:latest .

      - name: Import Image into K3s
        run: docker save arkintel:latest | sudo k3s ctr images import -

      - name: Rollout to K3s
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: |
          sudo kubectl rollout restart deployment/arkintel
          sudo kubectl rollout status deployment/arkintel --timeout=60s
